"""user-commit

Revision ID: 8c4cabe574d9
Revises: da763a8c6188
Create Date: 2021-05-29 16:49:14.893930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4cabe574d9'
down_revision = 'da763a8c6188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
