"""data-upload-commit

Revision ID: a44877f422da
Revises: 8c4cabe574d9
Create Date: 2021-05-29 16:50:21.423344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44877f422da'
down_revision = '8c4cabe574d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
