# This is a basic workflow to help you get started with Actions

name: Expo CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the deploy_branch branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: Build and Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # Runs a single command using the runners shell
      - uses: expo/expo-github-action@v5
        with:
              expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
              expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
              expo-cache: true
      - name: yarn install and build apk
#         working-directory: ./native-frontend-v1
      # Runs a set of commands using the runners shell
        run: |
          yarn --cwd ./native-frontend-v1 install
          expo build:android -t apk ./native-frontend-v1
